language: ruby
before_install:
  - gem install bundler -v  '~> 1.5'
before_script:
  - psql -c 'create database routes_api_test;' -U postgres
addons:
  postgresql: "9.4.1"
rvm:
  - 1.9.3
  - 2.2.1
  - 2.2.2
script: rake test
