language: ruby
before_install:
  - sudo /etc/init.d/postgresql start 9.4
  - gem install bundler -v  '~> 1.5'
before_script:
  - psql -c 'create database routes_api_test;' -U postgres
addons:
  postgresql: "9.4.1"
rvm:
  - 2.0.0
  - 2.2.1
  - 2.2.2
script:
  - RACK_ENV=test rake db:migrate
  - rake test
