---
development:
  adapter: postgresql
  host: localhost
  username: 'matheusrosa'
  password: ''
  database: 'routes_api_development'

test:
  adapter: postgresql
  host: localhost
  username: 'matheusrosa'
  password: ''
  database: 'routes_api_test'

production:
  adapter: postgresql
  host: localhost
  username: ''
  password: ''
  database: 'routes_api'
